### ISSUE TITLE
Please add LICENSE

### ISSUE THREAD

**Issue by bernhardschmidt** [alexjurkiewicz/apq#1]
Thanks for your work. Please add a license to your repository to make the copyright status of your work clear.

https://help.github.com/articles/adding-a-license-to-a-repository/

A safe choice is probably the MIT license.

**Comment by alexjurkiewicz** [comment]
I've added you as collaborator, please add MIT or release into the public domain as I did for https://github.com/alexjurkiewicz/acts/

**Comment by alexjurkiewicz** [comment]
https://github.com/alexjurkiewicz/acts/commit/ac5de7451a0a128f610f1e100b6e9b002479ccca, specifically
